config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get '/articles' => 'articles#index', as: 'articles'
  get '/articles/new' => 'articles#new', as: 'new_article'
  post '/articles' => 'articles#create', as: 'create_article'
  get '/articles/:id' => 'articles#show', as: 'show_article'
  get '/articles/:id/edit' => 'articles#edit', as: 'edit_article'
  patch '/articles/:id' => 'articles#update', as: 'update_article'
  delete '/articles/:id' => 'articles#delete', as: 'delete_article'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :name, presence: true,
                    uniqueness: true
    validates :body, presence: true,
                    length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.create(article_params)

        if @article.save
            redirect_to articles_path
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])

        if @article.update(article_params)
            redirect_to show_article_path
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def delete
        @article = Article.find(params[:id])
        @article.destroy

        redirect_to articles_path
    end

    private

    def article_params
        params.require(:article).permit(:name, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<div>
    <% if @article.errors.any? %>
        <ul>
            <% @article.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    <% end %>
</div>

<%= form_with scope: :article, url: update_article_path, method: :patch, local: true do |form| %>

    <div>
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>

    <div>
        <%= form.label :body %>
        <%= form.text_field :body %>
    </div>

    <div>
        <%= form.submit 'Update Article', class: "super-button" %>
    </div>

<% end %>

<%= link_to 'Cancel', :back, class: 'super-button' %>

app/views/articles/index.html.erb
<div class="w-[min(1200px,100%_-_2rem_*_2)] mx-auto my-4 rounded-2xl shadow-md overflow-hidden">
    <div class="flex flex-wrap justify-between items-center px-4 py-4">
        <span class="text-xl font-semibold">Article Index</span>
        <%= link_to 'Create Article', new_article_path, class: "super-button" %>
    </div>
    <table class="block text-left">
        <thead class="block bg-neutral-100">
            <tr class="grid grid-cols-[0.5fr_1fr_2fr_1fr] px-4 py-2">
                <th>ID</th>
                <th>Article Name</th>
                <th>Article Body</th>
                <th> </th>
            </tr>
        </thead>
        <tbody class="block">
            <% @articles.each do |article| %>
                <tr class="grid grid-cols-[0.5fr_1fr_2fr_1fr] px-4 py-2 border-solid border-b-[1px] border-slate-900/[0.1]">
                    <td><%= article.id %></td>
                    <td><%= article.name %></td>
                    <td><%= article.body %></td>
                    <td class="flex gap-4 items-center">
                        <%= link_to icon('fa-solid', 'magnifying-glass'), show_article_path(article), class: "super-link" %>
                        <%= link_to icon('fa-solid', 'pen-to-square'), edit_article_path(article), class: "super-link" %>
                        <%= button_to icon('fa-solid', 'trash'), delete_article_path(article), class: "super-link", method: :delete %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/articles/new.html.erb
<div>
    <% if @article.errors.any? %>
        <ul>
            <% @article.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    <% end %>
</div>

<%= form_with scope: :article, url: create_article_path, local: true do |form| %>

    <div>
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>

    <div>
        <%= form.label :body %>
        <%= form.text_field :body %>
    </div>

    <div>
        <%= form.submit 'Create Article', class: "super-button" %>
    </div>

<% end %>

<%= link_to 'Cancel', articles_path, class: 'super-button' %>

app/views/articles/show.html.erb
<p>ID: <%= @article.id %></P>
<p>Article Name: <%= @article.name %></P>
<p>Article Body: <%= @article.body %></P>
<%= link_to 'Edit article', edit_article_path, class: 'super-button' %>
<%= button_to 'delete article', delete_article_path, method: :delete, class: 'super-button' %>
<%= link_to 'Back to index', articles_path, class: 'super-button' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyOnRailsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="min-h-screen min-w-[320px]">
      <%= yield %>
    </main>
  </body>
</html>